# Generated by Django 4.1.4 on 2022-12-28 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_rename_servicios_servicio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicio',
            old_name='udpated',
            new_name='updated',
        ),
    ]
