# Generated by Django 4.1.4 on 2022-12-28 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='categorias',
            new_name='categoria',
        ),
    ]
