# Generated by Django 4.1.4 on 2022-12-28 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_categorias_post_categoria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='categoria',
            new_name='categorias',
        ),
    ]
